export const classes = [
  {
    title: "Beginner Karate",
    description: "Introduction to Karate",
    martialArt: "KARATE",
    level: "BEGINNER",
    minAge: 8,
    duration: 60,
    overview: "Learn basic strikes, kicks and kata.",
    capacity: 25,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869878/Jiu-Jitsu_jq3uja.jpg",
  },
  {
    title: "Advanced Karate",
    description: "Advanced Karate techniques and sparring.",
    martialArt: "KARATE",
    level: "ADVANCED",
    minAge: 14,
    duration: 90,
    overview: "Master advanced kata, kumite and self-defense techniques.",
    capacity: 15,
    beltRequirement: "Brown Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869878/judo_dbcyrf.jpg",
  },
  {
    title: "Karate Kids Training",
    description: "Karate classes for children.",
    martialArt: "KARATE",
    level: "BEGINNER",
    minAge: 6,
    duration: 45,
    overview: "Build discipline, balance and confidence.",
    capacity: 20,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Intermediate Karate",
    description: "Develop Karate skills beyond basics.",
    martialArt: "KARATE",
    level: "INTERMEDIATE",
    minAge: 10,
    duration: 75,
    overview: "Improve combinations, timing and techniques.",
    capacity: 20,
    beltRequirement: "Yellow Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/karate_o1wrvm.jpg",
  },

  {
    title: "Beginner Taekwondo",
    description: "Learn basic Taekwondo movements.",
    martialArt: "TAEKWONDO",
    level: "BEGINNER",
    minAge: 8,
    duration: 60,
    overview: "Learn kicks, blocks and basic forms.",
    capacity: 25,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "sarah@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Advanced Taekwondo",
    description: "Improve your kicking techniques.",
    martialArt: "TAEKWONDO",
    level: "ADVANCED",
    minAge: 12,
    duration: 90,
    overview: "Advanced sparring and forms.",
    capacity: 20,
    beltRequirement: "Blue Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "sarah@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Taekwondo Competition Training",
    description: "Competition-focused training.",
    martialArt: "TAEKWONDO",
    level: "ADVANCED",
    minAge: 15,
    duration: 120,
    overview: "Prepare for tournaments and professional matches.",
    capacity: 15,
    beltRequirement: "Red Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "sarah@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Jiu Jitsu Fundamentals",
    description: "Ground fighting basics.",
    martialArt: "JIU_JITSU",
    level: "BEGINNER",
    minAge: 15,
    duration: 75,
    overview: "Learn submissions and escapes.",
    capacity: 18,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "david@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Advanced Brazilian Jiu Jitsu",
    description: "Advanced grappling techniques.",
    martialArt: "JIU_JITSU",
    level: "ADVANCED",
    minAge: 16,
    duration: 120,
    overview: "Advanced submissions, transitions and rolling.",
    capacity: 12,
    beltRequirement: "Blue Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "david@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Jiu Jitsu Self Defense",
    description: "Practical self defense techniques.",
    martialArt: "JIU_JITSU",
    level: "INTERMEDIATE",
    minAge: 18,
    duration: 90,
    overview: "Learn real-world defensive techniques.",
    capacity: 20,
    beltRequirement: "White Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "david@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Beginner Judo",
    description: "Introduction to Judo.",
    martialArt: "JUDO",
    level: "BEGINNER",
    minAge: 10,
    duration: 60,
    overview: "Learn throws, balance and movement.",
    capacity: 20,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Judo Advanced Techniques",
    description: "Advanced throwing techniques.",
    martialArt: "JUDO",
    level: "ADVANCED",
    minAge: 14,
    duration: 90,
    overview: "Improve competitive Judo skills.",
    capacity: 15,
    beltRequirement: "Green Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Muay Thai Basics",
    description: "Learn traditional Muay Thai.",
    martialArt: "MUAY_THAI",
    level: "BEGINNER",
    minAge: 12,
    duration: 60,
    overview: "Learn punches, kicks, knees and elbows.",
    capacity: 25,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "david@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Muay Thai Fighter Training",
    description: "Intensive Muay Thai training.",
    martialArt: "MUAY_THAI",
    level: "ADVANCED",
    minAge: 18,
    duration: 120,
    overview: "Advanced conditioning and fight preparation.",
    capacity: 15,
    beltRequirement: "Intermediate Level",
    isActive: true,
    isPublished: true,
    instructorEmail: "david@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Kung Fu Beginner",
    description: "Traditional Kung Fu introduction.",
    martialArt: "KUNG_FU",
    level: "BEGINNER",
    minAge: 8,
    duration: 60,
    overview: "Learn basic forms and movements.",
    capacity: 20,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Kung Fu Weapons Training",
    description: "Traditional weapon techniques.",
    martialArt: "KUNG_FU",
    level: "ADVANCED",
    minAge: 16,
    duration: 90,
    overview: "Learn traditional martial arts weapons.",
    capacity: 10,
    beltRequirement: "Advanced Level",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Aikido Fundamentals",
    description: "Learn Aikido principles.",
    martialArt: "AIKIDO",
    level: "BEGINNER",
    minAge: 12,
    duration: 60,
    overview: "Study harmony, movement and control.",
    capacity: 20,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Aikido Intermediate",
    description: "Develop advanced Aikido movements.",
    martialArt: "AIKIDO",
    level: "INTERMEDIATE",
    minAge: 15,
    duration: 90,
    overview: "Improve techniques and partner exercises.",
    capacity: 15,
    beltRequirement: "Yellow Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "takashi@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },

  {
    title: "Martial Arts Fitness",
    description: "Fitness training using martial arts.",
    martialArt: "KARATE",
    level: "BEGINNER",
    minAge: 18,
    duration: 60,
    overview: "Improve strength, flexibility and endurance.",
    capacity: 30,
    beltRequirement: "None",
    isActive: true,
    isPublished: true,
    instructorEmail: "sarah@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
  {
    title: "Elite Martial Arts Program",
    description: "Professional level martial arts training.",
    martialArt: "KARATE",
    level: "ADVANCED",
    minAge: 18,
    duration: 120,
    overview: "Complete martial arts development program.",
    capacity: 10,
    beltRequirement: "Black Belt",
    isActive: true,
    isPublished: true,
    instructorEmail: "sarah@dojo.com",
    imageUrl:
      "https://res.cloudinary.com/d5tnusci/image/upload/v1784869879/Kids_Martial_Arts_hczkkm.jpg",
  },
];
